language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install: pip install .
before_script:
  - pip install -r tests/requirements.txt
script: nosetests --with-coverage --cover-erase --cover-package hubspot.connection
after_success:
  - coveralls
