language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
install: pip install --use-mirrors .
before_script:
  - pip install -r tests/requirements.txt --use-mirrors
script:  coverage run --source=hubspot.contacts setup.py test
after_success:
  - coveralls
