language: python
python:
  - "2.7"
install: pip install --use-mirrors .
before_script:
  - pip install -r tests/requirements.txt --use-mirrors
script:  coverage run --source=hubspot.connection setup.py test
after_success:
  - coveralls
